In [24]:
import numpy as np
from sklearn.datasets import load_iris
from collections import defaultdict
from operator import itemgetter

In [25]:
dataset = load_iris()


In [26]:
X = dataset.data
Y = dataset.target
#print(X)
#print(Y)

In [27]:
attribute_means=X.mean(axis = 0)
#print(attribute_means)


In [28]:
X_d = np.array(X >= attribute_means, dtype= 'int')
#print(X_d)

[[0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [0 0 1 1]
 [1 0 1 1]
 [0 0 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 0 1 1]
 [0 0 1 1]
 [0 0 0 0]
 [1 0 1 1]
 [1 0 1 0]
 [1 0 1 1]
 [0 0 0 1]
 [1 1 1 1]
 [0 0 1 1]
 [0 0 1 0]
 [1 0 1 1]
 [0 0 1 0]
 [1 1 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [1 0 1 1]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 1 1]
 [1 0 1 1]
 [0 0 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 0 1 1]
 [0 0 1 1]
 [0 0 1 1]
 [0 0 1 1]

In [ ]:
def train_feature_value(X, y_true, feature_index, value):
    class_counts = defaultdict(int)
    for sample, y in zip(X, y_true) :
        if sample[feature_index] == value:
            class_counts[y] += 1
    sorted_class_counts = sorted(class_counts.items(), key= itemgetter(1), reverse= True)
    most_freq_class = sorted_class_counts[0][0]
